"""LangGraph orchestration for the complete retrieval-augmented generation flow."""

from typing import Sequence, TypedDict

from langgraph.graph import END, START, StateGraph

from app.config import get_settings
from app.generation.llm_service import get_llm_service
from app.generation.prompt_builder import RAGPrompt, build_rag_prompt
from app.retrieval.retriever import RetrievedChunk, retrieve_chunks

NO_CONTEXT_ANSWER = "I couldn't find that information in the selected documents."


class RAGSource(TypedDict):
    """A source derived from retrieved metadata, never generated by the LLM."""

    source_number: int
    document_id: int
    filename: str
    page_number: int
    chunk_index: int
    score: float


class RAGResult(TypedDict):
    """Final answer and its retrieval-backed sources."""

    answer: str
    sources: list[RAGSource]


class RAGState(TypedDict, total=False):
    """Data passed between RAG graph nodes."""

    question: str
    user_id: int
    document_ids: Sequence[int] | None
    top_k: int | None
    score_threshold: float
    chunks: list[RetrievedChunk]
    prompt: RAGPrompt
    answer: str
    sources: list[RAGSource]


def retrieve_context(state: RAGState) -> RAGState:
    """Retrieve semantically similar chunks within the user's ownership boundary."""
    chunks = retrieve_chunks(
        question=state["question"],
        user_id=state["user_id"],
        document_ids=state.get("document_ids"),
        top_k=state.get("top_k"),
    )
    return {"chunks": chunks}


def filter_context(state: RAGState) -> RAGState:
    """Remove chunks below the configured cosine-similarity threshold."""
    threshold = state["score_threshold"]
    return {"chunks": [chunk for chunk in state["chunks"] if chunk["score"] >= threshold]}


def create_prompt(state: RAGState) -> RAGState:
    """Build grounded system and user prompts from the filtered context."""
    return {"prompt": build_rag_prompt(state["question"], state["chunks"])}


def generate_answer(state: RAGState) -> RAGState:
    """Generate an answer, or return a deterministic no-context response."""
    if not state["chunks"]:
        return {"answer": NO_CONTEXT_ANSWER}
    prompt = state["prompt"]
    answer = get_llm_service().generate(prompt.user, system_prompt=prompt.system)
    return {"answer": answer}


def collect_sources(state: RAGState) -> RAGState:
    """Create source records directly from retrieved metadata."""
    sources: list[RAGSource] = [
        {
            "source_number": source_number,
            "document_id": chunk["document_id"],
            "filename": chunk["filename"],
            "page_number": chunk["page_number"],
            "chunk_index": chunk["chunk_index"],
            "score": chunk["score"],
        }
        for source_number, chunk in enumerate(state["chunks"], start=1)
    ]
    return {"sources": sources}


def build_rag_graph():
    """Compile the modular RAG execution graph."""
    graph = StateGraph(RAGState)
    graph.add_node("retrieve", retrieve_context)
    graph.add_node("filter", filter_context)
    graph.add_node("prompt", create_prompt)
    graph.add_node("generate", generate_answer)
    graph.add_node("sources", collect_sources)
    graph.add_edge(START, "retrieve")
    graph.add_edge("retrieve", "filter")
    graph.add_edge("filter", "prompt")
    graph.add_edge("prompt", "generate")
    graph.add_edge("generate", "sources")
    graph.add_edge("sources", END)
    return graph.compile()


RAG_GRAPH = build_rag_graph()


def run_rag(
    question: str,
    user_id: int,
    document_ids: Sequence[int] | None = None,
    top_k: int | None = None,
    score_threshold: float | None = None,
) -> RAGResult:
    """Run the complete synchronous RAG pipeline for one authenticated user."""
    normalized_question = question.strip()
    if not normalized_question:
        raise ValueError("Question cannot be empty")
    if user_id < 1:
        raise ValueError("user_id must be positive")
    if document_ids is not None and not document_ids:
        raise ValueError("document_ids cannot be empty when provided")

    threshold = (
        score_threshold
        if score_threshold is not None
        else get_settings().retrieval_score_threshold
    )
    if not -1 <= threshold <= 1:
        raise ValueError("score_threshold must be between -1 and 1")

    result = RAG_GRAPH.invoke(
        {
            "question": normalized_question,
            "user_id": user_id,
            "document_ids": document_ids,
            "top_k": top_k,
            "score_threshold": threshold,
        }
    )
    return {"answer": result["answer"], "sources": result["sources"]}
