"""LangGraph orchestration for the complete retrieval-augmented generation flow."""

from collections.abc import Iterator
from typing import Literal, Sequence, TypedDict

from langgraph.graph import END, START, StateGraph

from app.chains.conversational_rag import ConversationMemoryMessage
from app.config import get_settings
from app.generation.llm_service import get_llm_service
from app.generation.prompt_builder import RAGPrompt, build_rag_prompt
from app.retrieval.retriever import RetrievedChunk, retrieve_chunks

NO_CONTEXT_ANSWER = "I couldn't find that information in the selected documents."

ConfidenceLevel = Literal["high", "medium", "low", "none"]

# ---------- confidence thresholds ----------
# Bands are based on BGE-small-en-v1.5 cosine-similarity score ranges.
# Confidence is calculated from the mean score of the top-3 surviving chunks.
CONFIDENCE_HIGH_THRESHOLD = 0.75
CONFIDENCE_MEDIUM_THRESHOLD = 0.50
CONFIDENCE_TOP_N = 3


class RAGSource(TypedDict):
    """A source derived from retrieved metadata, never generated by the LLM."""

    source_number: int
    document_id: int
    filename: str
    page_number: int
    chunk_index: int
    score: float
    text: str


class RAGResult(TypedDict):
    """Final answer and its retrieval-backed sources."""

    answer: str
    sources: list[RAGSource]
    confidence: ConfidenceLevel


class RAGSourcesEvent(TypedDict):
    """Retrieval metadata sent independently from model-generated text."""

    type: Literal["sources"]
    sources: list[RAGSource]
    confidence: ConfidenceLevel


class RAGTokenEvent(TypedDict):
    """One text fragment received directly from the LLM provider stream."""

    type: Literal["token"]
    token: str


class RAGDoneEvent(TypedDict):
    """Terminal marker for a successfully completed stream."""

    type: Literal["done"]


RAGStreamEvent = RAGSourcesEvent | RAGTokenEvent | RAGDoneEvent


class RAGState(TypedDict, total=False):
    """Data passed between RAG graph nodes."""

    question: str
    conversation_history: Sequence[ConversationMemoryMessage]
    user_id: int
    document_ids: Sequence[int] | None
    top_k: int | None
    score_threshold: float
    chunks: list[RetrievedChunk]
    prompt: RAGPrompt
    answer: str
    sources: list[RAGSource]


# ────────────────────────── quality helpers ──────────────────────────


def calculate_confidence(chunks: list[RetrievedChunk]) -> ConfidenceLevel:
    """Derive a retrieval confidence band from the top-N chunk scores.

    The confidence is purely a function of Qdrant cosine-similarity scores —
    never generated or influenced by the LLM.

    Bands:
        high   — avg score of top-N chunks ≥ 0.75
        medium — avg score ≥ 0.50
        low    — avg score < 0.50
        none   — no chunks survived the threshold filter
    """
    if not chunks:
        return "none"
    top_scores = sorted(
        (chunk["score"] for chunk in chunks), reverse=True
    )[:CONFIDENCE_TOP_N]
    avg_score = sum(top_scores) / len(top_scores)
    if avg_score >= CONFIDENCE_HIGH_THRESHOLD:
        return "high"
    if avg_score >= CONFIDENCE_MEDIUM_THRESHOLD:
        return "medium"
    return "low"


# ────────────────────────── graph nodes ──────────────────────────


def retrieve_context(state: RAGState) -> RAGState:
    """Retrieve semantically similar chunks within the user's ownership boundary."""
    chunks = retrieve_chunks(
        question=state["question"],
        user_id=state["user_id"],
        document_ids=state.get("document_ids"),
        top_k=state.get("top_k"),
    )
    return {"chunks": chunks}


def filter_context(state: RAGState) -> RAGState:
    """Remove chunks below the configured cosine-similarity threshold."""
    threshold = state["score_threshold"]
    return {"chunks": [chunk for chunk in state["chunks"] if chunk["score"] >= threshold]}


def create_prompt(state: RAGState) -> RAGState:
    """Build grounded system and user prompts from the filtered context."""
    return {
        "prompt": build_rag_prompt(
            state["question"],
            state["chunks"],
            state.get("conversation_history"),
        )
    }


def generate_answer(state: RAGState) -> RAGState:
    """Generate an answer, or return a deterministic no-context response."""
    if not state["chunks"]:
        return {"answer": NO_CONTEXT_ANSWER}
    prompt = state["prompt"]
    answer = get_llm_service().generate(prompt.user, system_prompt=prompt.system)
    return {"answer": answer}


def collect_sources(state: RAGState) -> RAGState:
    """Create source records directly from retrieved metadata."""
    sources: list[RAGSource] = [
        {
            "source_number": source_number,
            "document_id": chunk["document_id"],
            "filename": chunk["filename"],
            "page_number": chunk["page_number"],
            "chunk_index": chunk["chunk_index"],
            "score": chunk["score"],
            "text": chunk["text"],
        }
        for source_number, chunk in enumerate(state["chunks"], start=1)
    ]
    return {"sources": sources}


# ────────────────────────── graph construction ──────────────────────────


def build_rag_graph():
    """Compile the modular RAG execution graph."""
    graph = StateGraph(RAGState)
    graph.add_node("retrieve", retrieve_context)
    graph.add_node("filter", filter_context)
    graph.add_node("prompt", create_prompt)
    graph.add_node("generate", generate_answer)
    graph.add_node("sources", collect_sources)
    graph.add_edge(START, "retrieve")
    graph.add_edge("retrieve", "filter")
    graph.add_edge("filter", "prompt")
    graph.add_edge("prompt", "generate")
    graph.add_edge("generate", "sources")
    graph.add_edge("sources", END)
    return graph.compile()


RAG_GRAPH = build_rag_graph()


# ────────────────────────── public entry points ──────────────────────────


def create_initial_state(
    question: str,
    user_id: int,
    document_ids: Sequence[int] | None = None,
    top_k: int | None = None,
    score_threshold: float | None = None,
    conversation_history: Sequence[ConversationMemoryMessage] | None = None,
) -> RAGState:
    """Validate common RAG inputs and build the initial orchestration state."""
    normalized_question = question.strip()
    if not normalized_question:
        raise ValueError("Question cannot be empty")
    if user_id < 1:
        raise ValueError("user_id must be positive")
    if document_ids is not None and not document_ids:
        raise ValueError("document_ids cannot be empty when provided")

    settings = get_settings()

    # Clamp top_k to the configured ceiling so clients can't overload Qdrant.
    effective_top_k = top_k
    if effective_top_k is not None:
        effective_top_k = min(effective_top_k, settings.retrieval_max_top_k)

    threshold = (
        score_threshold
        if score_threshold is not None
        else settings.retrieval_score_threshold
    )
    if not -1 <= threshold <= 1:
        raise ValueError("score_threshold must be between -1 and 1")

    return {
        "question": normalized_question,
        "conversation_history": list(conversation_history or []),
        "user_id": user_id,
        "document_ids": document_ids,
        "top_k": effective_top_k,
        "score_threshold": threshold,
    }


def run_rag(
    question: str,
    user_id: int,
    document_ids: Sequence[int] | None = None,
    top_k: int | None = None,
    score_threshold: float | None = None,
    conversation_history: Sequence[ConversationMemoryMessage] | None = None,
) -> RAGResult:
    """Run the complete synchronous RAG pipeline for one authenticated user."""
    initial_state = create_initial_state(
        question=question,
        user_id=user_id,
        document_ids=document_ids,
        top_k=top_k,
        score_threshold=score_threshold,
        conversation_history=conversation_history,
    )
    result = RAG_GRAPH.invoke(initial_state)
    return {
        "answer": result["answer"],
        "sources": result["sources"],
        "confidence": calculate_confidence(result["chunks"]),
    }


def stream_rag(
    question: str,
    user_id: int,
    document_ids: Sequence[int] | None = None,
    top_k: int | None = None,
    score_threshold: float | None = None,
    conversation_history: Sequence[ConversationMemoryMessage] | None = None,
) -> Iterator[RAGStreamEvent]:
    """Yield retrieval sources and real Ollama text fragments as they arrive."""
    state = create_initial_state(
        question=question,
        user_id=user_id,
        document_ids=document_ids,
        top_k=top_k,
        score_threshold=score_threshold,
        conversation_history=conversation_history,
    )
    state.update(retrieve_context(state))
    state.update(filter_context(state))
    state.update(collect_sources(state))
    confidence = calculate_confidence(state["chunks"])
    yield {
        "type": "sources",
        "sources": state["sources"],
        "confidence": confidence,
    }

    if not state["chunks"]:
        yield {"type": "token", "token": NO_CONTEXT_ANSWER}
        yield {"type": "done"}
        return

    state.update(create_prompt(state))
    prompt = state["prompt"]
    for token in get_llm_service().stream_generate(
        prompt.user,
        system_prompt=prompt.system,
    ):
        yield {"type": "token", "token": token}
    yield {"type": "done"}
